import assert from "node:assert/strict";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { anchors } from "./check-docs.mjs";
import { portCatalog } from "./port-catalog.mjs";

const root = new URL("../", import.meta.url);
const read = (path) => readFileSync(new URL(path, root), "utf8");
export const published = JSON.parse(read("docs/published-installations.json"));
const prerelease = (port, version) =>
  port === "python" ? /(?:a|b|rc|dev)\d/i.test(version) : version.includes("-");

export function installCommand(port, record) {
  const id = portCatalog[port].packageId;
  switch (port) {
    case "typescript":
      return `npm install ${id}`;
    case "rust":
      return `cargo add ${id}`;
    case "go":
      return `go get ${id}@latest`;
    case "dart":
      return `dart pub add ${id}\n# Flutter: flutter pub add ${id}`;
    case "python":
      return `python -m pip install ${prerelease(port, record.version) ? "--pre " : ""}${id}`;
    case "csharp":
      return `dotnet add package ${id}${prerelease(port, record.version) ? " --prerelease" : ""}`;
    case "kotlin":
      return `repositories { mavenCentral() }\ndependencies { implementation("${id}:${record.version}") }`;
    case "swift":
      return `.package(url: "https://github.com/deancochran/ftms.git", revision: "${record.revision}")`;
    case "c":
      return `curl -fLO https://github.com/deancochran/ftms/releases/download/c-v${record.version}/ftms-c-${record.version}.tar.gz\nprintf '%s  %s\\n' '${record.sha256}' 'ftms-c-${record.version}.tar.gz' | sha256sum -c -`;
    default:
      throw new Error(`unknown port: ${port}`);
  }
}

export function render(records = published) {
  assert.deepEqual(Object.keys(records).sort(), Object.keys(portCatalog).sort());
  let output = `# Install FTMS in your application

<!-- Generated by tools/install-docs.mjs from published-installations.json. -->

Use the package manager's normal release selection for a new application, then
retain its resolved version and lockfile. These commands are not instructions to
make existing builds float on every run. Existing dependencies, SDK constraints
and registry configuration can affect resolution; check what was installed.

The records below describe verified public artifacts, not candidate manifests.
Latest-selection commands may resolve a newer release than our recorded evidence.
Read its changelog before adopting it. Non-prerelease 0.x does not promise a stable
1.0 interface. No 1.0 publication is implied here.

## Choose an installation

`;
  for (const port of [
    "c",
    "csharp",
    "dart",
    "go",
    "kotlin",
    "python",
    "rust",
    "swift",
    "typescript",
  ]) {
    const record = records[port];
    assert.match(record.version, /^\d+\.\d+\.\d+(?:[a-zA-Z0-9.+-]*)$/);
    assert.match(record.evidence, /^[a-z0-9-]+$/);
    if (port === "swift") assert.match(record.revision, /^[a-f0-9]{40}$/);
    if (port === "c") assert.match(record.sha256, /^[a-f0-9]{64}$/);
    output += `### ${portCatalog[port].language}\n\nRecorded release: **${record.version}** ([evidence](released-packages.md#${record.evidence})).\n\n`;
    if ((port === "python" || port === "csharp") && prerelease(port, record.version))
      output +=
        "The command explicitly includes prereleases; the recorded package is a prerelease, not a stable-API promise. Inspect and lock the resolved version.\n\n";
    output += `\`\`\`${port === "swift" ? "swift" : port === "kotlin" ? "kotlin" : "sh"}\n${installCommand(port, record)}\n\`\`\`\n\n`;
    if (port === "c")
      output +=
        "Verify before extracting. This command uses curl and sha256sum; Windows users can compare with Get-FileHash. Public Conan/vcpkg registry availability is not assumed.\n\n";
    if (port === "kotlin")
      output +=
        "Use this concrete verified dependency, not Gradle `+` or `latest.release`. Review dependency updates deliberately.\n\n";
    if (port === "swift")
      output +=
        "Add this entry to your Package.swift dependencies and select the FTMS product. Keep the immutable revision: this monorepo's language-prefixed tags are not SwiftPM version-range releases. Do not follow main.\n\n";
    output += `[Continue with the ${portCatalog[port].language} guide](../packages/${port}/README.md).\n\n`;
  }
  return `${output}## Reproduce or upgrade an example

Repository quickstarts retain exact dependencies or lockfiles so their assertions
are reproducible. Historical compatibility fixtures remain pinned. They are not
the default installation policy for a new application. To try a newer dependency,
update it deliberately, rerun the example tests, and inspect the resolved version.
For Python use a virtual environment and your project's dependency-locking tool;
pip install alone does not create a lockfile.

For C and Swift do not use the repository-wide GitHub latest-release URL: it may
identify another language. Concrete instructions above are refreshed only after
public verification, through the [release process](releasing.md).
`;
}

export function validateEvidence(records, ledger) {
  const current = ledger.split("## Current verified releases\n")[1]?.split("\n## ")[0];
  assert.ok(current, "Current verified releases table is required");
  for (const [port, record] of Object.entries(records)) {
    const row = current
      .split("\n")
      .find((line) => line.startsWith(`| ${portCatalog[port].language} |`));
    assert.ok(
      row?.includes(`](#${record.evidence})`),
      `${port}: evidence must match current table`,
    );
    const versions = row.split("|")[2].match(/\d+\.\d+\.\d+(?:[a-zA-Z0-9.+-]*)/g) ?? [];
    assert.deepEqual(versions, [record.version], `${port}: version must match current table`);
    const section = ledger
      .split(/(?=^## )/m)
      .find((part) => anchors(part.split("\n")[0]).has(record.evidence));
    assert.ok(section, `${port}: evidence section missing`);
    for (const value of [record.revision, record.sha256].filter(Boolean)) {
      assert.ok(
        section.includes(value),
        `${port}: immutable identity missing from evidence section`,
      );
    }
  }
}

export function check() {
  assert.equal(read("docs/install.md"), render(), "Run pnpm docs:install:generate");
  validateEvidence(published, read("docs/released-packages.md"));
  assert.match(read("docs/ftms-explained.md"), /^npm install @deancochran\/ftms$/m);
  for (const port of ["typescript", "rust", "go", "dart", "python", "csharp"]) {
    const command = installCommand(port, published[port]).split("\n")[0];
    assert.ok(
      read(`packages/${port}/README.md`).includes(`\n${command}\n`),
      `${port}: install command drift`,
    );
  }
  // These package-local snippets also appear in package registry READMEs.
  assert.ok(read("packages/kotlin/README.md").includes(installCommand("kotlin", published.kotlin)));
  assert.ok(read("packages/swift/README.md").includes(installCommand("swift", published.swift)));
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  assert.ok(
    process.argv.length === 3 && ["--write", "--check"].includes(process.argv[2]),
    "Usage: install-docs.mjs --write|--check",
  );
  if (process.argv[2] === "--write") writeFileSync(new URL("docs/install.md", root), render());
  else check();
}
